#!/usr/bin/env python3
"""
SymbioAI — TRUE Interventional Causality Experiment Runner
============================================================

Self-contained runner. Works from the repo root after:

    git clone --recurse-submodules https://github.com/ZulAmi/symbioAI.git
    cd symbioAI
    pip install -e ".[tracking,viz]"
    python run_optimized_true_causality.py [options]

Mammoth is included as a git submodule (mammoth/).
This script registers derpp-causal with Mammoth automatically on first run.

Modes (--use_causal_sampling):
    0  Vanilla DER++        ~43 min / seed
    1  Graph heuristic      ~43 min / seed
    2  Hybrid               ~2 h / seed
    3  TRUE causality       ~3-5 h / seed  (optimised from ~13 h)
    4  Influence functions  ~2 h / seed (est.)

Examples:
    # Smoke test — vanilla, 1 epoch (~5 min)
    python run_optimized_true_causality.py --use_causal_sampling 0 --n_epochs 1 --seed 1

    # TRUE causality, 5 epochs, log to W&B
    python run_optimized_true_causality.py --use_causal_sampling 3 --seed 1 --wandb

    # All 5 seeds (vanilla + TRUE)
    for seed in 1 2 3 4 5; do
        python run_optimized_true_causality.py --use_causal_sampling 0 --seed $seed
        python run_optimized_true_causality.py --use_causal_sampling 3 --seed $seed
    done
"""

import argparse
import os
import subprocess
import sys
from pathlib import Path

# ── Repo layout ───────────────────────────────────────────────────────────────
REPO_ROOT = Path(__file__).resolve().parent
MAMMOTH_DIR = REPO_ROOT / "mammoth"
MAMMOTH_MAIN = MAMMOTH_DIR / "utils" / "main.py"
SHIM_PATH = MAMMOTH_DIR / "models" / "derpp_causal.py"


def check_submodule() -> None:
    """Make sure the mammoth submodule is initialised."""
    if not MAMMOTH_MAIN.exists():
        print(
            "ERROR: mammoth submodule not initialised.\n"
            "Run:  git submodule update --init --recursive"
        )
        sys.exit(1)


def register_model() -> None:
    """
    Write a shim into mammoth/models/derpp_causal.py so Mammoth's
    os.listdir('models') discovers 'derpp-causal'.

    The shim force-registers the 'training' package in sys.modules before
    importing, because Mammoth does os.chdir() to its own root which can
    cause Python to find a non-package 'training' before our training/ dir.
    """
    shim = (
        "# Auto-generated by run_optimized_true_causality.py — do not edit.\n"
        "import sys as _sys, os as _os, types as _types\n"
        "# mammoth/models/derpp_causal.py -> mammoth/models -> mammoth -> repo_root\n"
        "_repo_root = _os.path.dirname(_os.path.dirname(_os.path.dirname(_os.path.abspath(__file__))))\n"
        "_training_dir = _os.path.join(_repo_root, 'training')\n"
        "# Force-register 'training' as a package so Mammoth's os.chdir() cannot\n"
        "# cause Python to find a non-package 'training' module first.\n"
        "if not isinstance(_sys.modules.get('training'), _types.ModuleType) or \\\n"
        "        not hasattr(_sys.modules.get('training'), '__path__'):\n"
        "    _pkg = _types.ModuleType('training')\n"
        "    _pkg.__path__ = [_training_dir]\n"
        "    _pkg.__package__ = 'training'\n"
        "    _pkg.__file__ = _os.path.join(_training_dir, '__init__.py')\n"
        "    _sys.modules['training'] = _pkg\n"
        "if _repo_root not in _sys.path:\n"
        "    _sys.path.insert(0, _repo_root)\n"
        "from training.derpp_causal import DerppCausal, DERPPCausal  # noqa: F401\n"
    )
    if not SHIM_PATH.exists() or SHIM_PATH.read_text() != shim:
        SHIM_PATH.write_text(shim)
        print(f"Registered derpp-causal with Mammoth → {SHIM_PATH.relative_to(REPO_ROOT)}")


def check_environment() -> None:
    try:
        import torch
        cuda = torch.cuda.is_available()
        device = torch.cuda.get_device_name(0) if cuda else "CPU"
        print(f"PyTorch {torch.__version__} | CUDA: {cuda} | Device: {device}")
    except ImportError:
        print("WARNING: PyTorch not installed — run: pip install -e '.[tracking,viz]'")


# ── CLI ───────────────────────────────────────────────────────────────────────

def main() -> int:
    parser = argparse.ArgumentParser(
        description="Run SymbioAI causal continual learning experiments",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog=__doc__,
    )

    # Core experiment
    parser.add_argument("--use_causal_sampling", type=int, default=3,
                        help="0=vanilla, 1=heuristic, 2=hybrid, 3=TRUE, 4=influence (default: 3)")
    parser.add_argument("--n_epochs", type=int, default=5,
                        help="Epochs per task (default: 5; literature standard: 50)")
    parser.add_argument("--seed", type=int, default=1)
    parser.add_argument("--batch_size", type=int, default=32)
    parser.add_argument("--buffer_size", type=int, default=500)

    # DER++ hyperparameters
    parser.add_argument("--alpha", type=float, default=0.1)
    parser.add_argument("--beta", type=float, default=0.5)
    parser.add_argument("--lr", type=float, default=0.03)

    # Causal tuning
    parser.add_argument("--true_micro_steps", type=int, default=1)
    parser.add_argument("--causal_hybrid_candidates", type=int, default=100)
    parser.add_argument("--causal_eval_interval", type=int, default=5)

    # Output / logging
    parser.add_argument("--output_dir", default="validation/results/runs")
    parser.add_argument("--output_name", default=None)
    parser.add_argument("--wandb", action="store_true",
                        help="Enable W&B logging (requires WANDB_API_KEY env var)")
    parser.add_argument("--debug", type=int, default=0)

    args = parser.parse_args()

    # ── Setup ─────────────────────────────────────────────────────────────────
    check_submodule()
    register_model()
    check_environment()

    mode_labels = {0: "vanilla", 1: "heuristic", 2: "hybrid", 3: "true", 4: "influence"}
    mode_name = mode_labels.get(args.use_causal_sampling, f"mode{args.use_causal_sampling}")

    out_dir = REPO_ROOT / args.output_dir
    out_dir.mkdir(parents=True, exist_ok=True)
    log_name = args.output_name or f"{mode_name}_seed{args.seed}_{args.n_epochs}ep.log"
    log_path = out_dir / log_name

    print(f"\nMode : {mode_name} (use_causal_sampling={args.use_causal_sampling})")
    print(f"Seed : {args.seed}  |  Epochs: {args.n_epochs}  |  Log: {log_path.relative_to(REPO_ROOT)}\n")

    # ── Build command ─────────────────────────────────────────────────────────
    cmd = [
        sys.executable, str(MAMMOTH_MAIN),
        "--model", "derpp-causal",
        "--dataset", "seq-cifar100",
        "--buffer_size", str(args.buffer_size),
        "--alpha", str(args.alpha),
        "--beta", str(args.beta),
        "--n_epochs", str(args.n_epochs),
        "--batch_size", str(args.batch_size),
        "--lr", str(args.lr),
        "--lr_scheduler", "multisteplr",
        "--lr_milestones", "3", "4",
        "--use_causal_sampling", str(args.use_causal_sampling),
        "--temperature", "2.0",
        "--true_micro_steps", str(args.true_micro_steps),
        "--true_temp_lr", "0.05",
        "--causal_hybrid_candidates", str(args.causal_hybrid_candidates),
        "--causal_eval_interval", str(args.causal_eval_interval),
        "--causal_num_interventions", "50",
        "--causal_effect_threshold", "0.05",
        "--causal_blend_ratio", "0.3",
        "--causal_batch_size", "16",
        "--causal_warmup_tasks", "2",
        "--use_batched_causality", "1",
        "--debug", str(args.debug),
        "--seed", str(args.seed),
    ]

    if args.wandb:
        if not os.environ.get("WANDB_API_KEY"):
            print("WARNING: --wandb set but WANDB_API_KEY not found in environment")
        cmd += ["--wandb", "True",
                "--wandb_project", "causal-continual-learning",
                "--wandb_name", f"{mode_name}_seed{args.seed}"]

    # ── Environment for subprocess ────────────────────────────────────────────
    env = os.environ.copy()
    # Ensure both repo root and mammoth are on PYTHONPATH for the subprocess
    existing = env.get("PYTHONPATH", "")
    env["PYTHONPATH"] = f"{REPO_ROOT}{os.pathsep}{MAMMOTH_DIR}{os.pathsep}{existing}".rstrip(os.pathsep)

    print("Command:")
    print("  " + " \\\n  ".join(cmd))
    print()

    # ── Run ───────────────────────────────────────────────────────────────────
    with log_path.open("w") as fh:
        proc = subprocess.Popen(
            cmd,
            stdout=subprocess.PIPE,
            stderr=subprocess.STDOUT,
            text=True,
            bufsize=1,
            cwd=str(MAMMOTH_DIR),   # Mammoth expects to run from its own root
            env=env,
        )
        for line in proc.stdout:
            print(line, end="")
            fh.write(line)
            fh.flush()
        proc.wait()

    print(f"\nExit code : {proc.returncode}")
    print(f"Log saved : {log_path}")

    # Extract and print final accuracy line
    try:
        for line in reversed(log_path.read_text().splitlines()):
            if "Class-IL" in line and "%" in line:
                print(f"Result    : {line.strip()}")
                break
    except Exception:
        pass

    return proc.returncode


if __name__ == "__main__":
    sys.exit(main())
